# Generated by Django 4.2.5 on 2023-09-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="category",
            field=models.CharField(
                choices=[
                    ("Supermarkets", "Supermarkets"),
                    ("Accounts", "Accounts"),
                    ("Other", "Other"),
                ],
                default=1,
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
