# Generated by Django 4.2.5 on 2023-10-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="cost",
            options={"verbose_name_plural": "Расходы"},
        ),
        migrations.AlterField(
            model_name="cost",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category",
                to="api.category",
            ),
        ),
    ]
